analyser: fix multiprocessing issue
Fuzz Introspector is failed when building reports for Tarantool
and other projects, see [1]:

```
  File "/usr/local/lib/python3.10/multiprocessing/managers.py", line 817, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/fuzz-introspector/src/fuzz_introspector/datatypes/fuzzer_profile.py", line 359, in accummulate_profile
    return_dict[uniq_id] = self
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'
```

The issue is related to processing data in parallel mode and
happen due to a bug in CPython 3.10.0. The patch fixes the issue
by using Queue.

1. https://github.com/google/oss-fuzz/issues/13226

Related to #2267
Related to google/oss-fuzz#13226

Signed-off-by: Sergey Bronnikov <estetus@gmail.com>